### ISSUE TITLE
Dead link to paper in README.md

### ISSUE THREAD

**Issue by Wolf-SO** [RUB-SysSec/Marx#2]
The link behind *MARX: Uncovering Class Hierarchies in C++ Programs* is dead. Do you maybe mean one of these:

- https://download.vusec.net/papers/marx_ndss17.pdf
- https://www.ndss-symposium.org/ndss2017/ndss-2017-programme/marx-uncovering-class-hierarchies-c-programs/

**Comment by RUB-SysSec** [comment]
Thank you, the link is fixed.
